### ISSUE TITLE
Option to log header errors

### ISSUE THREAD

**Issue by jwestbrook** [roadrunner2/mod-proxy-protocol#3]
On my AWS EC2 instances the apache logs get constantly filled with errors from the ProxyProtocol module because the ELB health checks do not send a ProxyProtocol header with their checks.

```
ProxyProtocol: no valid header found
```

Can this log entry be turned into a option so I do not have to turn off all errors? Or possibly point me in the direction to disable them with the current version?

**Comment by roadrunner2** [comment]
The cleaner way to solve this, IMO, is to have Apache listen on two ports, one with ProxyProtocol enabled, and one without; then configure the ELB to forward requests to the port with ProxyProtocol enabled, but to run the health checks against the other port. Not only does this avoid noise in the log, but it means that the ELB can actually do a proper health check (otherwise the connection just gets aborted, severely limiting the effectiveness of the health check).

Btw., see https://github.com/roadrunner2/mod-proxy-protocol/pull/2#issuecomment-196142975 for a skeleton of how to do this setup.
